theme: minima
title: JennXBlog
author: JenxJennx
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
   On this site we will be discussing various topics and new trends. 
   Fashion, technology, lifestyle, nature, and everything in between.

# social links
twitter_username: JenxJennx # DO NOT include the @ character, or else the build will fail!
github_username:  JenxJennx # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
